### ISSUE TITLE
Problem with launcher

### ISSUE THREAD

**Issue by LucaVerzeroli-PhD** [pedroeml/checkpoint-mobile-access-vpn#1]
Hi,
thank you for the guide.. 
I'm at the last step.
I run ./launcher but it stacks on
LAUNCHER> Starting CShell...

Can you help me?

**Comment by pedroeml** [comment]
Hi @LucaVerzeroliUnibg 
Are you at the post-install section of the tutorial? If so, probably you forgot to disable the launcher script at the Ubuntu Startup Applications. 

If not, the CShell launcher is stuck because there is another CShell launcher process running in your machine. Try to find it and run the `kill` command on it to end the process. Then you should be fine when running CShell `./launcher`. If it doesn't work, probably there are more CShell launcher processes running. In this case it might be easier to just restart your machine.
